name: Arize Onboard Manual Trigger

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Project ID'
        required: true
      env:
        description: 'Environment'
        required: true
        default: 'prod'
        type: choice
        options:
          - dev
          - prod

jobs:
  run-python:
    runs-on: ubuntu-latest

    env:
      # ---------- DEV CONFIG ----------
      dev_domains: "optum.com,uhc.com,uhg.com"
      dev_authorizer: "https://login.microsoftonline.com"
      dev_tenant_id: "db05faca-c82a-4b9d-b9c5-0f64b6755421"
      dev_path: "/federationmetadata/2007-06/federationmetadata.xml"
      dev_app_id: "46ccd4fc-c9c9-4146-8941-44792fec9b28"

      # ---------- PROD CONFIG ----------
      prod_domains: "optum.com,uhc.com,uhg.com"
      prod_authorizer: "https://login.microsoftonline.com"
      prod_tenant_id: "db05faca-c82a-4b9d-b9c5-0f64b6755421"
      prod_path: "/federationmetadata/2007-06/federationmetadata.xml"
      prod_app_id: "46ccd4fc-c9c9-4146-8941-44792fec9b2"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - run: pip install gql requests

      - name: Set env vars
        run: |
          if [ "${{ github.event.inputs.env }}" = "dev" ]; then
            echo "SUPPORTED_DOMAINS=${{ env.dev_domains }}" >> $GITHUB_ENV
            echo "AUTHORIZER_BASE_URL=${{ env.dev_authorizer }}" >> $GITHUB_ENV
            echo "TENANT_ID=${{ env.dev_tenant_id }}" >> $GITHUB_ENV
            echo "AUTHORIZER_URL_PATH=${{ env.dev_path }}" >> $GITHUB_ENV
            echo "APP_ID=${{ env.dev_app_id }}" >> $GITHUB_ENV
            echo "ARIZE_GRAPHQL_URL=https://arize-dev.example.com/graphql" >> $GITHUB_ENV
          else
            echo "SUPPORTED_DOMAINS=${{ env.prod_domains }}" >> $GITHUB_ENV
            echo "AUTHORIZER_BASE_URL=${{ env.prod_authorizer }}" >> $GITHUB_ENV
            echo "TENANT_ID=${{ env.prod_tenant_id }}" >> $GITHUB_ENV
            echo "AUTHORIZER_URL_PATH=${{ env.prod_path }}" >> $GITHUB_ENV
            echo "APP_ID=${{ env.prod_app_id }}" >> $GITHUB_ENV
            echo "ARIZE_GRAPHQL_URL=https://arize-prod.example.com/graphql" >> $GITHUB_ENV
          fi

      - name: Run script
        run: python arize/main.py ${{ github.event.inputs.projectId }} ${{ github.event.inputs.env }}
        env:
          ARIZE_API_KEY: dummy_api_key